services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: satellite_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./apps/server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/server:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:password@db:5432/satellite_db
    depends_on:
      - db
  redis:
    image: redis:alpine
    restart: always

  worker:
    build: ./apps/server
    command: celery -A celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:password@db:5432/satellite_db
      - REDIS_URL=redis://redis:6379/0
  beat:
    build: ./apps/server
    command: celery -A celery_app beat --loglevel=info
    depends_on:
      - redis

  bot:
    build: ./apps/bot
    command: python main.py
    env_file:
      - ./apps/bot/.env
    depends_on:
      - api

volumes:
  postgres_data:
